version: '3'

services:
  app1:

    build: ./app
    
    links:
      - database

    depends_on:
      - database

    ports:
      - '5000:5000'

    networks:
      - netw
    
  app2:

    build:  ./app

    links:
      - database

    depends_on:
      - database
      
    ports:
      - '5001:5000'

    networks:
      - netw

  app3:

    build: ./app

    links:
      - database

    depends_on:
      - database
      
    ports:
      - '5002:5000'

    networks:
      - netw

  database:

    image: mysql:5.6

    volumes:
      - ./database/elsword.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data:/var/lib/mysql

    environment:
      MYSQL_ROOT_PASSWORD: root

    ports:
      - "32000:3306"
    networks:
      - netw

  nginx:

    image: nginx


    volumes:
      - ./load_balancer/default.conf:/etc/nginx/conf.d/default.conf

    depends_on:
      - app1
      - app2
      - app3

    ports:
      - "8080:80"

    networks:
      - netw

networks:
  netw:
    
    
    