FROM python:3.8

WORKDIR /app

COPY ./requirements.txt /app

RUN pip install -r requirements.txt

COPY main.py /app

COPY templates /app/templates

COPY static /app/static

EXPOSE 5001

ENV FLASK_APP=main.py
CMD ["flask", "run", "--host", "0.0.0.0"]
